name: model-training   # name of our workflow

on: [push] 

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # ML workflow comes here
          pip install -r requirements.txt
          python train.py
        
          # write your CML report
          cat metrics.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md # publish an image for writing into CML report
          cml-send-comment report.md   # Return CML report as a comment 